config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'github_search#index'

  resources :github_search, only: [:index]
end

app/models/concerns/github_repo.rb
# frozen_string_literal: true

class GithubRepo
  include ActiveModel::Model

  attr_accessor :name, :full_name, :owner_name, :description, :language, :stars

  SEARCH_DEFAULTS = { page: 1, per_page: 50, sort: 'stars', order: 'desc' }.freeze

  class << self
    def all(query_params)
      params_with_defaults = github_search_params_with_defaults(query_params)
      response = HTTParty.get(github_search_url(params_with_defaults))
      response_body = JSON.parse(response.body)
      map_github_repos_response(response_body['items'])
    end

    def github_search_params_with_defaults(params)
      params ||= {}
      SEARCH_DEFAULTS.merge(params.to_h.symbolize_keys)
    end

    private

    def github_search_url(params)
      search_url = 'https://api.github.com/search/repositories?q='
      search_url += "#{params[:search]} in:name+" if params[:search].present?
      search_url += "stars:>=0&page=#{params[:page]}&per_page=#{params[:per_page]}" \
              "&sort=#{params[:sort]}&order=#{params[:order]}"
    end

    def map_github_repos_response(repos)
      repos.map do |repo|
        GithubRepo.new(
          name: repo['name'],
          full_name: repo['full_name'],
          owner_name: repo['owner']['login'],
          description: repo['description'],
          language: repo['language'],
          stars: repo['stargazers_count']
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github_search_controller.rb
# frozen_string_literal: true

class GithubSearchController < ApplicationController
  def index
    @params_with_defaults = GithubRepo.github_search_params_with_defaults(github_search_params)
    @github_repos = GithubRepo.all(github_search_params)
  end

  private

  def github_search_params
    params[:github_search]&.permit(:search, :sort, :order)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/github_search/index.html.erb
<div class="container">
  <h2 class="title is-2">Github repositories</h2>
  <div class="level">
    <%= form_for :github_search, url: url_for(github_search_index_path()), method: "GET" do |form| %>
      <span class="level-item">
        <%= 
          form.text_field(
            "search",
            placeholder: "Search Repository name",
            class: "input",
            value: @params_with_defaults[:search]
          )
        %>
      </span>
      <span class="level-item">
        <span class="level-description">Sort by</span>
        <div class="select">
          <%= 
            form.select(
              "sort", 
              options_for_select([["Stars", "stars"], ["Time created", "created"]], @params_with_defaults[:sort]),
            )
          %>
        </div>
      </span>
      <span class="level-item">
        <span class="level-description">Order by</span>
        <div class="select">
          <%= 
            form.select(
              "order", 
              options_for_select([["Descendent", "desc"], ["Ascendent", "asc"]], @params_with_defaults[:order]),
            ) 
          %>
        </div>
      </span>
      <span class="level-item">
        <div class="control">
          <%= form.submit("search", class: "button is-primary") %>
        </div>
      </span>
    <% end %>
  </div>
</div>

<div class="container">
  <table class="table">
    <thead>
      <th><%= "Name" %></th>
      <th><%= "Full Name" %></th>
      <th><%= "Owner Name" %></th>
      <th><%= "Description" %></th>
      <th><%= "Language" %></th>
      <th><%= "Stars" %></th>
    </thead>
    
    <% @github_repos.each do |repo| %>
      <tr>
        <td><%= repo.name %></td>
        <td><%= repo.full_name %></td>
        <td><%= repo.owner_name %></td>
        <td><%= repo.description %></td>
        <td><%= repo.language %></td>
        <td><%= repo.stars %></td>
      </tr>
    <% end %>
  </table>

  <div class="level">
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>